# Generated by Django 4.1.3 on 2025-03-04 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard'), ('4', 'Extreme')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('distance', models.CharField(max_length=10)),
                ('image', models.TextField(default='https://i.pinimg.com/564x/42/23/7b/42237b9fd34b36ad15aca8788f6c9339.jpg')),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.TextField(default='https://i.pinimg.com/564x/42/23/7b/42237b9fd34b36ad15aca8788f6c9339.jpg')),
                ('bio', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FloatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.float')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='float',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.user'),
        ),
        migrations.AddField(
            model_name='float',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.difficulty'),
        ),
        migrations.AddField(
            model_name='float',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.rating'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_on', models.DateField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.user')),
                ('float', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.float')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefloatapi.rating')),
            ],
        ),
    ]
