# Generated by Django 4.1.3 on 2025-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefloatapi', '0002_alter_float_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
